name: Build

on:
  pull_request:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.x
            9.x
            10.x
          dotnet-quality: 'ga'

      - name: Build solution
        working-directory: src
        run: dotnet build

      - name: Run unit-tests
        working-directory: src
        run: dotnet test
